defaults:
  - hydra/sweeper: optuna

hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: minimize  # or maximize (i don't know)
    storage: null 
    study_name: null  
    n_trials: 20  
    n_jobs: 1 
    search_space:
      learning_rate:
        type: float
        bounds: [0.0001, 0.1]
        log: true
      batch_size:
        type: int
        bounds: [16, 128]
      num_layers:
        type: int
        bounds: [1, 5]